#!/usr/bin/env node

require('app-module-path').addPath(__dirname)
var program = require('lib/program')
var commands = require('lib/commands')

program
  .option('-t, --token [token]', 'digitalocean api token')
  .parse(process.argv)

var args = program.token ? ['-e', 'do_token=' + program.token] : []

commands([
  ['ansible', 'init', args]
])
