#!/usr/bin/env node

require('app-module-path').addPath(__dirname)
var program = require('lib/program')
var _ = require('lodash')
var fs = require('fs-extra')
var commands = require('lib/commands')


program
  .arguments('<name>')
  .parse(process.argv)

if (program.args.length < 1) {
  program.exitWithError('please supply key name')
}

var name = program.args.shift()
var path = 'config/keys/' + name

// if (!fs.pathExistsSync(path)) {
//   program.exitWithError('key "' + name + '" does not exist')
// }

if (fs.pathExistsSync(path)) {
  fs.unlinkSync(path)
  console.log('key "' + name + '" removed')
}

commands([
  ['init', null],
  ['ansible', 'ssh']
])
