#!/usr/bin/env node

require('app-module-path').addPath(__dirname)
var _ = require('lodash')
var fs = require('fs-extra')

var keys = _.filter(fs.readdirSync('config/keys'), function(file) {
  return file[0] !== '.'
})

_.each(keys, function(key) {
  console.log(key)
  // console.log(key, '=>', fs.readFileSync('config/keys/' + key, 'utf8'))
})
