#!/usr/bin/env node

require('app-module-path').addPath(__dirname)
var program = require('lib/program')

var terraform = require('lib/terraform')('manager')
var keyFingerprint = require('lib/key')
var commands = require('lib/commands')


program
  .option('-n, --count [n]', 'number of managers', parseInt)
  .parse(process.argv)

program.count = program.count === undefined ? 1 : program.count
var token = require('lib/digitalocean').token()


commands([
  ['terraform.apply', 'manager', {
    state: '/state/manager.tfstate',
    var: [
      'do_token=' + token,
      'key_fingerprint=' + keyFingerprint,
      'manager_count=' + program.count
    ]
  }],
  'hosts.update',
  ['ansible', 'setup'],
  ['ansible', 'tag'],
  ['ansible', 'networking'],
  ['ansible', 'ssh'],
  ['ansible', 'docker']
])
