#!/usr/bin/env node

require('app-module-path').addPath(__dirname)
var program = require('lib/program')
var command = require('lib/commands/init')


program
  .option('-t, --token [token]', 'digitalocean api token')
  .parse(process.argv)

command(program.token)
