#!/usr/bin/env node

require('app-module-path').addPath(__dirname)
var program = require('lib/program')


program
  .command('ls', 'list ssh keys')
  .command('add', 'add ssh key')
  .command('rm', 'remove ssh key')
  .parse(process.argv)
