---

- name: checking swarm mode status
  command: docker info
  register: docker_info
  changed_when: false

- name: defining docker swarm manager address
  set_fact:
    swarm_manager_ip: "{{ ansible_eth1['ipv4']['address'] }}"

- name: init docker swarm mode
  command: >
    docker swarm init
      --advertise-addr "{{ swarm_manager_ip }}:2377"
  when: '"Swarm: inactive" in docker_info.stdout'

- name: capturing docker swarm worker join-token
  command: docker swarm join-token -q worker
  changed_when: false
  register: swarm_token_worker

- name: capturing docker swarm manager join-token
  command: docker swarm join-token -q manager
  changed_when: false
  register: swarm_token_manager

- name: storing swarm worker token
  copy:
    content: '{{ swarm_token_worker.stdout }}'
    dest: /config/swarm_token_worker
  delegate_to: localhost

- name: storing swarm manager token
  copy:
    content: '{{ swarm_token_manager.stdout }}'
    dest: /config/swarm_token_manager
  delegate_to: localhost

- name: storing swarm ip address
  copy:
    content: '{{ swarm_manager_ip }}'
    dest: /config/swarm_manager_ip
  delegate_to: localhost

- name: ensure traefik network
  docker_network:
    state: present
    name: traefik
    driver: overlay
